#!/bin/bash

# IP
##################
ip="192.168.1.204"
##################

# CONFIG
## 512x10, 1024x10, 2048x10, 512x20, 1024x20
##################
config=2048x10
##################

echo -e "\e[43mConnecting to LiDAR at $ip and setting $config configuration...\e[0m"

#set destination ip (this pc)
echo "set_config_param udp_ip $(hostname -I | cut -f 1 -d " ")" | nc $ip 7501 -q 1

if [ $? != "0" ]; then
	echo -e"\e[41mError setting ip dest $(hostname -I | cut -f 1 -d " ")\e[0m"
else
	echo -e "\e[42mSet ip dest $(hostname -I | cut -f 1 -d " ") (this pc)\e[0m"
fi

#set lidar mode
echo "set_config_param lidar_mode $config" | nc $ip 7501 -q 1
if [ $? != "0" ]; then
	echo -e "\e[41mError setting lidar mode $config\e[0m"
else
	echo -e "\e[42mSet lidar mode $config\e[0m"
fi

#Save configs
echo "write_config_txt" | nc $ip 7501 -q 1
if [ $? != "0" ]; then
	echo -e "\e[41mError saving configuration\e[0m"
else
	echo -e "\e[42mConfiguration saved for next reboots\e[0m"
fi

#start sensor
echo "reinitialize" | nc $ip 7501 -q 1
if [ $? != "0" ]; then
	echo -e "\e[41mError starting sensor\e[0m"
else
	echo -e "\e[42mSensor start successfully. You must attend 10 seconds\e[0m"
fi




