#include <string>
#include <sstream>
#include "tkversion_git.h" // generated by cmake

namespace tk { namespace common {

    std::string tkVersionGit() {
        return TKVERSION_GIT;
    }

    int tkVersion2Int(std::string version) {
        return stoi(version, 0, 16);
    }

    std::string tkVersion2String(int version) {
        std::stringstream sstream;
        sstream << std::hex << version;
        std::string ver = sstream.str();
        return ver;
    }

}}
